In [22]:
import requests
import pandas as pd
import numpy as np

In [23]:
#Open Meteo API  to make weather data

In [24]:
# i changed my API to this one bacause it has history weather data
#this is open API, so there is no key 
url = "https://archive-api.open-meteo.com/v1/archive?latitude=40.7128&longitude=-74.0060&start_date=2025-01-01&end_date=2026-04-09&daily=temperature_2m_mean,relative_humidity_2m_mean,cloudcover_mean,windspeed_10m_max&timezone=America/New_York"
#the coordinates are NY 
response = requests.get(url)
weather_data = response.json()

print(weather_data.keys())

dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'daily_units', 'daily'])

In [25]:
#creating dataframe with daily variables
daily = weather_data["daily"]

weather_df = pd.DataFrame(daily)

weather_df.head()

,time,temperature_2m_mean,relative_humidity_2m_mean,cloudcover_mean,windspeed_10m_max
0,2025-01-01,7.4,81,45,23.2
1,2025-01-02,2.6,56,33,25.1
2,2025-01-03,0.4,59,36,17.1
3,2025-01-04,-1.4,51,56,26.1
4,2025-01-05,-2.2,52,51,19.9

In [26]:
#renaming columns 
weather_df.columns = [
    "date",
    "temperature",
    "humidity",
    "cloud_cover",
    "wind_speed"
]

weather_df.head()

         date  temperature  humidity  cloud_cover  wind_speed
0  2025-01-01          7.4        81           45        23.2
1  2025-01-02          2.6        56           33        25.1
2  2025-01-03          0.4        59           36        17.1
3  2025-01-04         -1.4        51           56        26.1
4  2025-01-05         -2.2        52           51        19.9

In [27]:
weather_df.to_csv("weather_data.csv", index=False)

In [28]:
spy_df = pd.read_csv('/Users/liza/Desktop/ECO590/dataspyeco590.csv')
spy_df = spy_df.dropna(subset=["Date"]) 
spy_df["Date"] = pd.to_datetime(spy_df["Date"], format="%d/%m/%y") #check the format of the date 


spy_df.head()

,Date,PX_LAST,Change,% Change,PX_OPEN,Change.1,% Change.1,PX_HIGH,Change.2,% Change.2,PX_LOW,Change.3,% Change.3
0,2026-04-09,679.17,3.16,0.467449,674.84,-1.17,-0.173074,681.16,5.15,0.761823,673.77,-2.24,-0.331356
1,2026-04-08,676.01,16.79,2.546949,676.39,17.17,2.604593,677.08,17.86,2.709262,671.46,12.24,1.856740
2,2026-04-07,659.22,0.29,0.044011,656.65,-2.28,-0.346016,659.61,0.68,0.103198,651.06,-7.87,-1.194361
3,2026-04-06,658.93,3.10,0.472683,655.86,0.03,0.004574,659.72,3.89,0.593142,655.52,-0.31,-0.047268
4,2026-04-02,655.83,0.59,0.090043,646.42,-8.82,-1.346072,658.20,2.96,0.451743,645.11,-10.13,-1.545998

In [29]:
#renaming columns 
spy_df.columns = [
    "date",
    "close",
    "change_close",
    "daily_return",
    "open",
    "change_open",
    "return_open",
    "high",
    "change_high",
    "return_high",
    "low",
    "change_low",
    "return_low"
]
spy_df.head()

,date,close,change_close,daily_return,open,change_open,return_open,high,change_high,return_high,low,change_low,return_low
0,2026-04-09,679.17,3.16,0.467449,674.84,-1.17,-0.173074,681.16,5.15,0.761823,673.77,-2.24,-0.331356
1,2026-04-08,676.01,16.79,2.546949,676.39,17.17,2.604593,677.08,17.86,2.709262,671.46,12.24,1.856740
2,2026-04-07,659.22,0.29,0.044011,656.65,-2.28,-0.346016,659.61,0.68,0.103198,651.06,-7.87,-1.194361
3,2026-04-06,658.93,3.10,0.472683,655.86,0.03,0.004574,659.72,3.89,0.593142,655.52,-0.31,-0.047268
4,2026-04-02,655.83,0.59,0.090043,646.42,-8.82,-1.346072,658.20,2.96,0.451743,645.11,-10.13,-1.545998

In [30]:
#merging 2 datasets 
spy_df['date'] = pd.to_datetime(spy_df['date'])
weather_df['date'] = pd.to_datetime(weather_df['date'])

merged_df = pd.merge(spy_df, weather_df, on="date", how="inner")

merged_df.head()

,date,close,change_close,daily_return,open,change_open,return_open,high,change_high,return_high,low,change_low,return_low,temperature,humidity,cloud_cover,wind_speed
0,2026-04-09,679.17,3.16,0.467449,674.84,-1.17,-0.173074,681.16,5.15,0.761823,673.77,-2.24,-0.331356,4.9,71,23,13.9
1,2026-04-08,676.01,16.79,2.546949,676.39,17.17,2.604593,677.08,17.86,2.709262,671.46,12.24,1.856740,3.1,52,0,14.3
2,2026-04-07,659.22,0.29,0.044011,656.65,-2.28,-0.346016,659.61,0.68,0.103198,651.06,-7.87,-1.194361,7.6,53,38,23.3
3,2026-04-06,658.93,3.10,0.472683,655.86,0.03,0.004574,659.72,3.89,0.593142,655.52,-0.31,-0.047268,8.8,50,32,21.1
4,2026-04-02,655.83,0.59,0.090043,646.42,-8.82,-1.346072,658.20,2.96,0.451743,645.11,-10.13,-1.545998,8.1,79,100,21.7

In [32]:
merged_df = merged_df[["date", "close", "daily_return","temperature","humidity","cloud_cover","wind_speed"]]
merged_df.head()
#renaming columns

,date,close,daily_return,temperature,humidity,cloud_cover,wind_speed
0,2026-04-09,679.17,0.467449,4.9,71,23,13.9
1,2026-04-08,676.01,2.546949,3.1,52,0,14.3
2,2026-04-07,659.22,0.044011,7.6,53,38,23.3
3,2026-04-06,658.93,0.472683,8.8,50,32,21.1
4,2026-04-02,655.83,0.090043,8.1,79,100,21.7

In [ ]:
#creating new calculaed variable

In [36]:
merged_df["good_weather"] = (
    (merged_df["temperature"].between(5, 22)) &
    (merged_df["cloud_cover"] < 60) &
    (merged_df["wind_speed"] < 25)
).astype(int)
#my criteria for good weather 
merged_df.head()

,date,close,daily_return,temperature,humidity,cloud_cover,wind_speed,good_weather
0,2026-04-09,679.17,0.467449,4.9,71,23,13.9,0
1,2026-04-08,676.01,2.546949,3.1,52,0,14.3,0
2,2026-04-07,659.22,0.044011,7.6,53,38,23.3,1
3,2026-04-06,658.93,0.472683,8.8,50,32,21.1,1
4,2026-04-02,655.83,0.090043,8.1,79,100,21.7,0

In [37]:
merged_df["good_weather"].value_counts() #to look how many days match my criteria

good_weather
0    203
1     48
Name: count, dtype: int64

In [38]:
merged_df.to_csv("final_dataset.csv", index=False)

Regression description

Dependent variable:

daily_return Independent variables:

good_weather (main calculated varible) temperature humidity cloud_cover wind_speed First regression: daily_return = β0 + β1 * good_weather + β2 * temperature + β3 * humidity + β4 * cloud_cover + β5 * wind_speed + ε Main regression: daily_return = β0 + β1 * good_weather

The goal of regression is to test is the good wheather influence on stock market returns.